### PR TITLE
add context.type, context.path, context.method data to error

### PR DESCRIPTION
**Pull request by mkovel**
This data useful when you get try to one service method inside another patch -> get. 
and they have very similar rules.

### CODE REVIEW

**Comment by marshallswain** [comment]
Thanks!  I actually realized that this was needed, yesterday, so perfect timing to see that you've already done the work!  Thanks!

**Comment by marshallswain** [comment]
Now available on npm as `@feathers-plus/validate-joi@3.4.0`.

**Comment by marshallswain** [comment]
https://github.com/feathers-plus/validate-joi/releases/tag/v3.4.0

**Comment by mkovel** [comment]
welcome

**Pull request merged**
